### ISSUE TITLE
Error when clicking button

### ISSUE THREAD

**Issue by pesky-wobbit** [operation404/boneyard-drawing-tools#2]
Clicking either the fill or line bottom generates an error for me. No control pops up. 
Foundry v10 - 291
No other modules installed.

Foundry VTT | Rendering Drawing_Tools
foundry.js:747 Error: An error occurred while rendering Drawing_Tools 63. ENOENT: no such file or directory, open 'E:\FoundryVTT\Data\modules\boneyard\templates\color_selector.html'
    at i.<anonymous> (foundry.js:6883:41)
    at i.value (socket.js:309:17)
    at i.value (socket.js:239:22)
    at x.emit (index.mjs:136:20)
    at s.value (manager.js:200:14)
    at x.emit (index.mjs:136:20)
    at a.value (index.js:119:51)
    at s.value (manager.js:192:22)
    at x.emit (index.mjs:136:20)
    at a.value (socket.js:323:26)
onError @ foundry.js:747
(anonymous) @ foundry.js:5069
Promise.catch (async)
render @ foundry.js:5067
onClick @ drawing_tools.js:28
_onClickTool @ foundry.js:67697
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by operation404** [comment]
Thank you for catching this. It appears that a path wasn't updated after I split the original module this was a part of into multiple smaller modules. The path has been updated and a new version has been put out that should resolve the issue.
